### ISSUE TITLE
Proposition : create a list of shortcuts instead of functions

### ISSUE THREAD

**Issue by RCura** [jhollist/proj4shortcut#4]
Instead of creating many isolated functions as it's currently the case, you could create an object having a slot for each shortcut.
Just like the `leaflet::providers` works : this would allow for a very simple autocompletion and fast lookout of the availables shortcuts.

**Comment by jhollist** [comment]
Did something similar, but just switched from functions to exported character vectors.  Using slots and s4 objects seemed a bit much (plus I've not developed with them!)

Thanks for the idea.
